### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by EarningEye3** [james090500/MinecraftCapesBot#12]
Can u make it into a bot that will do something like:
- Set the cape from certain id's from database
- I saw a discord where you type in $showcape (id) [and u have an site IP in your hosts]
- If ts possible contact me on discord Monsterek#5113 I'm willing to pay

**Comment by EarningEye3** [comment]
I can give you the discord invite in dm's

**Comment by EarningEye3** [comment]
That the bot is in

**Comment by james090500** [comment]
Not relevant issue
